[project]
name = "orientation-project"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["flask>=3.1.1"]

[dependency-groups]
dev = ["pytest>=8.3.5", "ruff>=0.11.12"]
